---
- include_tasks:        '../tasks/dependencies.yml'
- include_tasks:        '../tasks/system_groups.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/install_files.yml'
